[package]
name = "bis"
repository = { workspace = true }
description = { workspace = true }
version = { workspace = true }
edition = { workspace = true }

[dependencies]
bis-core = { path = "../../core" }

anyhow = { workspace = true }
futures = { workspace = true }
log = { workspace = true }
mime = "0.3"
once_cell = { workspace = true }
rand = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true, features = [
    "runtime-tokio-rustls",
    "macros",
    "postgres",
    "uuid",
    "chrono",
    "json",
    "bit-vec",
] }
thiserror = { workspace = true }
tokio = { workspace = true, features = [
    "signal",
    "rt-multi-thread",
    "net",
    "time",
    "macros",
] }
toml = "0.5.9"

# Actix
actix-web = { version = "4.0", default-features = false, features = ["macros"] }
actix-http = "3.1.0"
actix-cors = "0.6.1"
actix-web-httpauth = "0.6.0"

bitcoin = { workspace = true }

# Atb
atb = { workspace = true }
atb-cli = { workspace = true }
atb-tokio-ext = { workspace = true }
