apiVersion: v1
data:
  config.toml: |
    magic = "main"
    provider_url = 'https://lively-fittest-log.btc.quiknode.pro/ad03c5276959ab662d466db6447d45fa6baa9336'
    poll_frequency_ms = 180000
    # `start_block` is optional.  If omitted, the newest block queried from the chain will
    # be the `start_block` value
    # start_block = 0
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: bis
  name: bis-cm0
