apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: bis
  name: bis
spec:
  containers:
    - args:
        - mono
      env:
        - name: BIS_POSTGRES
        - name: BTCUSER
        - name: BTCUSERPASSWORD
        - name: PGPASSWORD
        - name: PGPORT
        - name: RUST_LOG
          value: info,sqlx=warn
      image: gcr.io/ivanshyu/bis:latest
      name: bis
      ports:
        - containerPort: 3030
          protocol: TCP
      volumeMounts:
        - mountPath: /app/deployment/config.toml
          name: bis-cm0
          subPath: config.toml
  restartPolicy: OnFailure
  volumes:
    - configMap:
        items:
          - key: config_docker.toml
            path: config.toml
        name: bis-cm0
      name: bis-cm0
