apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: bis
  name: bis
spec:
  containers:
    - args:
        - mono
      env:
        - name: DATABASE_URL
          value: "postgresql://postgres:FG9xrwZCqZeIG77FHBVtnapx6JOGisIQCgPzWbzr+Z+g@postgres:5432/btc_indexer?sslmode=disable"
        - name: BIS_POSTGRES
          value: "postgresql://postgres:FG9xrwZCqZeIG77FHBVtnapx6JOGisIQCgPzWbzr+Z+g@postgres:5432/btc_indexer?sslmode=disable"
        - name: BTCUSER
          value: bitcoinrpc
        - name: BTCUSERPASSWORD
          value: FG9xrwZCqZeIG77FHBVtnapx6JOGisIQCgPzWbzr+Z+g
        - name: PGPASSWORD
          value: FG9xrwZCqZeIG77FHBVtnapx6JOGisIQCgPzWbzr+Z+g
        - name: PGPORT
          value: "5432"
        - name: RUST_LOG
          value: info,sqlx=warn
      image: gcr.io/ivanshyu/bis:latest
      name: bis
      ports:
        - containerPort: 3030
          protocol: TCP
      volumeMounts:
        - mountPath: /app/deployment/config.toml
          name: bis-cm0
          subPath: config.toml
  restartPolicy: OnFailure
  volumes:
    - configMap:
        items:
          - key: config.toml
            path: config.toml
        name: bis-cm0
      name: bis-cm0
