apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: btc-regtest
  name: btc-regtest
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: btc-regtest
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: btc-regtest
    spec:
      initContainers:
        - name: init-copy-config
          image: busybox
          command: ['sh', '-c', 'cp /config/bitcoin.conf /bitcoin/.bitcoin/']
          volumeMounts:
            - name: btc-regtest-config
              mountPath: /config
            - name: bitcoin-data
              mountPath: /bitcoin/.bitcoin
      containers:
        - image: kylemanna/bitcoind
          name: bitcoin-regtest
          ports:
            - containerPort: 18443
              protocol: TCP
            - containerPort: 18444
              protocol: TCP
          volumeMounts:
            - name: bitcoin-data
              mountPath: /bitcoin/.bitcoin
      volumes:
        - name: btc-regtest-config
          configMap:
            name: btc-regtest-cm0
        - name: bitcoin-data
          emptyDir: {}
