apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: btc-regtest
  name: btc-regtest
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: btc-regtest
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: btc-regtest
    spec:
      containers:
        - args:
            - -regtest=1
            - -rpcallowip=0.0.0.0/0
            - -rpcbind=0.0.0.0
            - -rpcuser=
            - -rpcpassword=
            - -server=1
            - -wallet=wallet.dat
            - -disablewallet=0
          env:
            - name: BITCOIN_DATA
              value: /efs/bitcoin-data
          image: kylemanna/bitcoind
          name: bitcoin-regtest
          ports:
            - containerPort: 18443
              protocol: TCP
            - containerPort: 18444
              protocol: TCP
          volumeMounts:
            - mountPath: /bitcoin/.bitcoin
              name: btc-regtest-cm0
      restartPolicy: Always
      volumes:
        - configMap:
            name: btc-regtest-cm0
          name: btc-regtest-cm0
