provider_url = 'http://bitcoin-testnet:19001'
poll_frequency_ms = 10000
# `start_block` is optional.  If omitted, the newest block queried from the chain will
# be the `start_block` value
# start_block = 0
