# The magic number for the Bitcoin network
# 0xD9B4BEF9(3652501241) => Some(Network::Bitcoin),
# 0x0709110B(118034699) => Some(Network::Testnet),
# 0x40CF030A(1087308554) => Some(Network::Signet),
# 0xDAB5BFFA(3669344250) => Some(Network::Regtest),
magic = 3669344250
provider_url = 'http://btc-regtest:18443'
poll_frequency_ms = 10000
# `start_block` is optional.  If omitted, the newest block queried from the chain will
# be the `start_block` value
# start_block = 0
